import type { Continent, Country } from '@/services/resources/country/types.ts'

export type GuessedCountry = { guessedAt: Date | null; country: Country }

export type GuessedCountriesMap = Record<Country['isoAlpha2Code'], GuessedCountry>

const chineseNames = {
  afghanistan: '阿富汗',
  albania: '阿尔巴尼亚',
  algeria: '阿尔及利亚',
  'american-samoa': '美属萨摩亚',
  andorra: '安道尔',
  angola: '安哥拉',
  anguilla: '安圭拉',
  antarctica: '南极洲',
  'antigua-and-barbuda': '安提瓜和巴布达',
  aruba: '阿鲁巴',
  argentina: '阿根廷',
  armenia: '亚美尼亚',
  australia: '澳大利亚',
  austria: '奥地利',
  azerbaijan: '阿塞拜疆',
  bahamas: '巴哈马',
  bahrain: '巴林',
  bangladesh: '孟加拉国',
  barbados: '巴巴多斯',
  belarus: '白俄罗斯',
  belgium: '比利时',
  belize: '伯利兹',
  benin: '贝宁',
  bermuda: '百慕大',
  bhutan: '不丹',
  bolivia: '玻利维亚',
  'bosnia-and-herzegovina': '波斯尼亚和黑塞哥维那',
  botswana: '博茨瓦纳',
  brazil: '巴西',
  'british-indian-ocean-territory': '英属印度洋领土',
  'british-virgin-islands': '英属维尔京群岛',
  'brunei-darussalam': '文莱',
  bulgaria: '保加利亚',
  'burkina-faso': '布基纳法索',
  burundi: '布隆迪',
  cambodia: '柬埔寨',
  cameroon: '喀麦隆',
  canada: '加拿大',
  'cape-verde': '佛得角',
  'cayman-islands': '开曼群岛',
  'central-african-republic': '中非共和国',
  chad: '查德',
  chile: '智利',
  china: '中国',
  'cote-d-ivoire': '科特迪瓦',
  colombia: '哥伦比亚',
  comoros: '科摩罗',
  congo: '刚果',
  'cook-islands': '库克群岛',
  'costa-rica': '哥斯达黎加',
  croatia: '克罗地亚',
  cuba: '古巴',
  curacao: '库拉索',
  cyprus: '塞浦路斯',
  'czech-republic': '捷克',
  'democratic-republic-of-the-congo': '刚果民主共和国',
  denmark: '丹麦',
  djibouti: '吉布提',
  dominica: '多米尼加',
  'dominican-republic': '多米尼加共和国',
  ecuador: '厄瓜多尔',
  egypt: '埃及',
  'el-salvador': '萨尔瓦多',
  'equatorial-guinea': '赤道几内亚',
  eritrea: '厄立特里亚',
  estonia: '爱沙尼亚',
  eswatini: '斯威士兰',
  ethiopia: '埃塞俄比亚',
  'falkland-islands': '福克兰群岛',
  'faroe-islands': '法罗群岛',
  fiji: '斐济',
  finland: '芬兰',
  france: '法国',
  'french-polynesia': '法属波利尼西亚',
  'french-southern-territories': '法属南部和南极领土',
  gabon: '加蓬',
  gambia: '冈比亚',
  georgia: '格鲁吉亚',
  germany: '德国',
  ghana: '加纳',
  gibraltar: '直布罗陀',
  greece: '希腊',
  greenland: '格陵兰',
  grenada: '格林纳达',
  guam: '关岛',
  guatemala: '危地马拉',
  guernsey: '根西岛',
  guinea: '几内亚',
  'guinea-bissau': '几内亚比绍',
  guyana: '圭亚那',
  haiti: '海地',
  'holy-see': '圣座',
  honduras: '洪都拉斯',
  hungary: '匈牙利',
  iceland: '冰岛',
  india: '印度',
  indonesia: '印度尼西亚',
  iran: '伊朗',
  iraq: '伊拉克',
  ireland: '爱尔兰',
  'isle-of-man': '马恩岛',
  israel: '以色列',
  italy: '意大利',
  jamaica: '牙买加',
  japan: '日本',
  jersey: '泽西岛',
  jordan: '约旦',
  kazakhstan: '哈萨克斯坦',
  kenya: '肯尼亚',
  kiribati: '基里巴斯',
  'korea-north': '朝鲜',
  'korea-south': '韩国',
  kuwait: '科威特',
  kyrgyzstan: '吉尔吉斯斯坦',
  laos: '老挝',
  latvia: '拉脱维亚',
  lebanon: '黎巴嫩',
  lesotho: '莱索托',
  liberia: '利比里亚',
  libya: '利比亚',
  liechtenstein: '列支敦士登',
  lithuania: '立陶宛',
  luxembourg: '卢森堡',
  madagascar: '马达加斯加',
  malawi: '马拉维',
  malaysia: '马来西亚',
  maldives: '马尔代夫',
  mali: '马里',
  malta: '马耳他',
  'marshall-islands': '马绍尔群岛',
  mauritania: '毛里塔尼亚',
  mauritius: '毛里求斯',
  mexico: '墨西哥',
  micronesia: '密克罗尼西亚',
  moldova: '摩尔多瓦',
  monaco: '摩纳哥',
  mongolia: '蒙古',
  montenegro: '黑山',
  montserrat: '蒙特塞拉特',
  morocco: '摩洛哥',
  mozambique: '莫桑比克',
  myanmar: '缅甸',
  namibia: '纳米比亚',
  nauru: '瑙鲁',
  nepal: '尼泊尔',
  netherlands: '荷兰',
  'new-caledonia': '新喀里多尼亚',
  'new-zealand': '新西兰',
  nicaragua: '尼加拉瓜',
  niger: '尼日尔',
  nigeria: '尼日利亚',
  niue: '纽埃',
  'north-macedonia': '北马其顿',
  'northern-mariana-islands': '北马里亚纳群岛',
  norway: '挪威',
  oman: '阿曼',
  pakistan: '巴基斯坦',
  palau: '帕劳',
  palestine: '巴勒斯坦',
  panama: '巴拿马',
  'papua-new-guinea': '巴布亚新几内亚',
  paraguay: '巴拉圭',
  peru: '秘鲁',
  philippines: '菲律宾',
  pitcairn: '皮特凯恩岛',
  poland: '波兰',
  portugal: '葡萄牙',
  'puerto-rico': '波多黎各',
  qatar: '卡塔尔',
  romania: '罗马尼亚',
  russia: '俄罗斯',
  rwanda: '卢旺达',
  'saint-barthelemy': '圣巴特勒米',
  'saint-helena': '圣赫勒拿',
  'saint-kitts-and-nevis': '圣基茨和尼维斯',
  'saint-lucia': '圣卢西亚',
  'saint-martin': '圣马丁',
  'saint-pierre-and-miquelon': '圣皮埃尔和米克隆',
  'saint-vincent-and-the-grenadines': '圣文森特和格林纳丁斯',
  samoa: '萨摩亚',
  'san-marino': '圣马力诺',
  'sao-tome-and-principe': '圣多美和普林西比',
  'saudi-arabia': '沙特阿拉伯',
  senegal: '塞内加尔',
  serbia: '塞尔维亚',
  seychelles: '塞舌尔',
  'sierra-leone': '塞拉利昂',
  singapore: '新加坡',
  'sint-maarten': '圣马丁岛',
  slovakia: '斯洛伐克',
  slovenia: '斯洛文尼亚',
  'solomon-islands': '所罗门群岛',
  somalia: '索马里',
  'south-africa': '南非',
  'south-georgia-and-the-south-sandwich-islands': '南乔治亚岛及南桑威奇群岛',
  'south-sudan': '南苏丹',
  spain: '西班牙',
  'sri-lanka': '斯里兰卡',
  sudan: '苏丹',
  suriname: '苏里南',
  sweden: '瑞典',
  switzerland: '瑞士',
  'syrian-arab-republic': '叙利亚阿拉伯共和国',
  taiwan: '台湾',
  tajikistan: '塔吉克斯坦',
  tanzania: '坦桑尼亚',
  thailand: '泰国',
  'timor-leste': '东帝汶',
  togo: '多哥',
  tokelau: '托克劳',
  tonga: '汤加',
  'trinidad-and-tobago': '特立尼达和多巴哥',
  tunisia: '突尼斯',
  turkey: '土耳其',
  turkmenistan: '土库曼斯坦',
  tuvalu: '图瓦卢',
  uganda: '乌干达',
  ukraine: '乌克兰',
  'united-arab-emirates': '阿联酋',
  'united-kingdom': '英国',
  'united-states': '美国',
  'united-states-virgin-islands': '美国维尔京群岛',
  uruguay: '乌拉圭',
  uzbekistan: '乌兹别克斯坦',
  vanuatu: '瓦努阿图',
  venezuela: '委内瑞拉',
  vietnam: '越南',
  yemen: '也门',
  zambia: '赞比亚',
  zimbabwe: '津巴布韦',
} as const satisfies Record<string, string>

const baseCountries: Array<
  Omit<Country, 'allowedGuesses'> & { allowedGuesses: Omit<Country['allowedGuesses'], 'zh'> }
> = [
  {
    name: 'Afghanistan',
    isoAlpha2Code: 'AF',
    continents: ['asia'],
    allowedGuesses: {
      en: ['afghanistan'],
      es: ['afganistán', 'afganistan'],
      pt: ['afeganistão', 'afeganistao'],
      de: ['afghanistan'],
    },
    slug: 'afghanistan',
  },
  {
    name: 'Albania',
    isoAlpha2Code: 'AL',
    continents: ['europe'],
    allowedGuesses: {
      en: ['albania'],
      es: ['albania'],
      pt: ['albânia', 'albania'],
      de: ['albanien'],
    },
    slug: 'albania',
  },
  {
    name: 'Algeria',
    isoAlpha2Code: 'DZ',
    continents: ['africa'],
    allowedGuesses: {
      en: ['algeria'],
      es: ['argelia'],
      pt: ['argélia', 'argelia'],
      de: ['algerien'],
    },
    slug: 'algeria',
  },
  {
    name: 'American Samoa',
    isoAlpha2Code: 'AS',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['american samoa'],
      es: ['samoa americana'],
      pt: ['samoa americana'],
      de: ['amerikanisch-samoa', 'amerikanisch samoa'],
    },
    slug: 'american-samoa',
  },
  {
    name: 'Andorra',
    isoAlpha2Code: 'AD',
    continents: ['europe'],
    allowedGuesses: { en: ['andorra'], es: ['andorra'], pt: ['andorra'], de: ['andorra'] },
    slug: 'andorra',
  },
  {
    name: 'Angola',
    isoAlpha2Code: 'AO',
    continents: ['africa'],
    allowedGuesses: { en: ['angola'], es: ['angola'], pt: ['angola'], de: ['angola'] },
    slug: 'angola',
  },
  {
    name: 'Anguilla',
    isoAlpha2Code: 'AI',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['anguilla'], es: ['anguilla'], pt: ['anguilla'], de: ['anguilla'] },
    slug: 'anguilla',
  },
  {
    name: 'Antarctica',
    isoAlpha2Code: 'AQ',
    continents: ['antarctica'],
    allowedGuesses: {
      en: ['antarctica'],
      es: ['antártida', 'antartida'],
      pt: ['antártica', 'antartica'],
      de: ['antarktis'],
    },
    slug: 'antarctica',
  },
  {
    name: 'Antigua and Barbuda',
    isoAlpha2Code: 'AG',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['antigua and barbuda'],
      es: ['antigua y barbuda'],
      pt: ['antígua e barbuda', 'antigua e barbuda'],
      de: ['antigua und barbuda'],
    },
    slug: 'antigua-and-barbuda',
  },
  {
    name: 'Aruba',
    isoAlpha2Code: 'AW',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['aruba'], es: ['aruba'], pt: ['aruba'], de: ['aruba'] },
    slug: 'aruba',
  },
  {
    name: 'Argentina',
    isoAlpha2Code: 'AR',
    continents: ['southAmerica'],
    allowedGuesses: {
      en: ['argentina'],
      es: ['argentina'],
      pt: ['argentina'],
      de: ['argentinien'],
    },
    slug: 'argentina',
  },
  {
    name: 'Armenia',
    isoAlpha2Code: 'AM',
    continents: ['asia', 'europe'],
    allowedGuesses: {
      en: ['armenia'],
      es: ['armenia'],
      pt: ['armênia', 'armenia'],
      de: ['armenien'],
    },
    slug: 'armenia',
  },
  {
    name: 'Australia',
    isoAlpha2Code: 'AU',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['australia'],
      es: ['australia'],
      pt: ['austrália', 'australia'],
      de: ['australien'],
    },
    slug: 'australia',
  },
  {
    name: 'Austria',
    isoAlpha2Code: 'AT',
    continents: ['europe'],
    allowedGuesses: {
      en: ['austria'],
      es: ['austria'],
      pt: ['áustria', 'austria'],
      de: ['oesterreich', 'österreich'],
    },
    slug: 'austria',
  },
  {
    name: 'Azerbaijan',
    isoAlpha2Code: 'AZ',
    continents: ['asia', 'europe'],
    allowedGuesses: {
      en: ['azerbaijan'],
      es: ['azerbaiyán', 'azerbaiyan'],
      pt: ['azerbaijão', 'azerbaijao'],
      de: ['aserbaidschan'],
    },
    slug: 'azerbaijan',
  },
  {
    name: 'Bahamas',
    isoAlpha2Code: 'BS',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['bahamas'], es: ['bahamas'], pt: ['bahamas'], de: ['bahamas'] },
    slug: 'bahamas',
  },
  {
    name: 'Bahrain',
    isoAlpha2Code: 'BH',
    continents: ['asia'],
    allowedGuesses: {
      en: ['bahrain'],
      es: ['baréin', 'barein'],
      pt: ['bareine', 'barein', 'bahrein', 'barein'],
      de: ['bahrain'],
    },
    slug: 'bahrain',
  },
  {
    name: 'Bangladesh',
    isoAlpha2Code: 'BD',
    continents: ['asia'],
    allowedGuesses: {
      en: ['bangladesh'],
      es: ['bangladés', 'banglades'],
      pt: ['bangladesh'],
      de: ['bangladesch'],
    },
    slug: 'bangladesh',
  },
  {
    name: 'Barbados',
    isoAlpha2Code: 'BB',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['barbados'], es: ['barbados'], pt: ['barbados'], de: ['barbados'] },
    slug: 'barbados',
  },
  {
    name: 'Belarus',
    isoAlpha2Code: 'BY',
    continents: ['europe'],
    allowedGuesses: {
      en: ['belarus'],
      es: ['bielorrusia'],
      pt: ['bielorrússia', 'bielorrussia', 'belarus'],
      de: ['belarus', 'weißrussland', 'weissrussland'],
    },
    slug: 'belarus',
  },
  {
    name: 'Belgium',
    isoAlpha2Code: 'BE',
    continents: ['europe'],
    allowedGuesses: {
      en: ['belgium'],
      es: ['bélgica', 'belgica'],
      pt: ['bélgica', 'belgica'],
      de: ['belgien'],
    },
    slug: 'belgium',
  },
  {
    name: 'Belize',
    isoAlpha2Code: 'BZ',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['belize'], es: ['belice'], pt: ['belize'], de: ['belize'] },
    slug: 'belize',
  },
  {
    name: 'Benin',
    isoAlpha2Code: 'BJ',
    continents: ['africa'],
    allowedGuesses: { en: ['benin'], es: ['benín', 'benin'], pt: ['benim'], de: ['benin'] },
    slug: 'benin',
  },
  {
    name: 'Bermuda',
    isoAlpha2Code: 'BM',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['bermuda'], es: ['bermudas'], pt: ['bermudas'], de: ['bermuda'] },
    slug: 'bermuda',
  },
  {
    name: 'Bhutan',
    isoAlpha2Code: 'BT',
    continents: ['asia'],
    allowedGuesses: {
      en: ['bhutan'],
      es: ['bután', 'butan'],
      pt: ['butão', 'butao'],
      de: ['bhutan'],
    },
    slug: 'bhutan',
  },
  {
    name: 'Bolivia',
    isoAlpha2Code: 'BO',
    continents: ['southAmerica'],
    allowedGuesses: {
      en: ['bolivia'],
      es: ['bolivia'],
      pt: ['bolívia', 'bolivia'],
      de: ['bolivien'],
    },
    slug: 'bolivia',
  },
  {
    name: 'Bosnia and Herzegovina',
    isoAlpha2Code: 'BA',
    continents: ['europe'],
    allowedGuesses: {
      en: ['bosnia and herzegovina', 'bosnia'],
      es: ['bosnia y herzegovina', 'bosnia'],
      pt: ['bósnia e herzegovina', 'bosnia e herzegovina', 'bósnia', 'bosnia'],
      de: ['bosnien und herzegowina', 'bosnien herzegowina', 'bosnien'],
    },
    slug: 'bosnia-and-herzegovina',
  },
  {
    name: 'Botswana',
    isoAlpha2Code: 'BW',
    continents: ['africa'],
    allowedGuesses: { en: ['botswana'], es: ['botsuana'], pt: ['botsuana'], de: ['botswana'] },
    slug: 'botswana',
  },
  {
    name: 'Brazil',
    isoAlpha2Code: 'BR',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['brazil'], es: ['brasil'], pt: ['brasil'], de: ['brasilien'] },
    slug: 'brazil',
  },
  {
    name: 'British Indian Ocean Territory',
    isoAlpha2Code: 'IO',
    continents: ['asia'],
    allowedGuesses: {
      en: ['british indian ocean territory'],
      es: ['territorio británico del océano Índico', 'territorio britanico del oceano indico'],
      pt: ['território britânico do oceano índico', 'territorio britanico do oceano indico'],
      de: ['britisches territorium im indischen ozean'],
    },
    slug: 'british-indian-ocean-territory',
  },
  {
    name: 'British Virgin Islands',
    isoAlpha2Code: 'VG',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['british virgin islands'],
      es: [
        'islas vírgenes británicas',
        'islas virgenes britanicas',
        'islas vírgenes',
        'islas virgenes',
      ],
      pt: ['ilhas virgens britânicas', 'ilhas virgens britanicas', 'ilhas virgens'],
      de: ['britische jungferninseln'],
    },
    slug: 'british-virgin-islands',
  },
  {
    name: 'Brunei Darussalam',
    isoAlpha2Code: 'BN',
    continents: ['asia'],
    allowedGuesses: {
      en: ['brunei', 'brunei darussalam'],
      es: ['brunéi', 'brunei darussalam'],
      pt: ['brunei', 'brunei darussalam'],
      de: ['brunei', 'brunei darussalam'],
    },
    slug: 'brunei-darussalam',
  },
  {
    name: 'Bulgaria',
    isoAlpha2Code: 'BG',
    continents: ['europe'],
    allowedGuesses: {
      en: ['bulgaria'],
      es: ['bulgaria'],
      pt: ['búlgaria', 'bulgaria'],
      de: ['bulgarien'],
    },
    slug: 'bulgaria',
  },
  {
    name: 'Burkina Faso',
    isoAlpha2Code: 'BF',
    continents: ['africa'],
    allowedGuesses: {
      en: ['burkina faso'],
      es: ['burkina faso'],
      pt: ['burkina faso'],
      de: ['burkina faso'],
    },
    slug: 'burkina-faso',
  },
  {
    name: 'Burundi',
    isoAlpha2Code: 'BI',
    continents: ['africa'],
    allowedGuesses: { en: ['burundi'], es: ['burundi'], pt: ['burundi'], de: ['burundi'] },
    slug: 'burundi',
  },
  {
    name: 'Cambodia',
    isoAlpha2Code: 'KH',
    continents: ['asia'],
    allowedGuesses: { en: ['cambodia'], es: ['camboya'], pt: ['camboja'], de: ['kambodscha'] },
    slug: 'cambodia',
  },
  {
    name: 'Cameroon',
    isoAlpha2Code: 'CM',
    continents: ['africa'],
    allowedGuesses: {
      en: ['cameroon'],
      es: ['camerún', 'camerun'],
      pt: ['camarões', 'camaroes'],
      de: ['kamerun'],
    },
    slug: 'cameroon',
  },
  {
    name: 'Canada',
    isoAlpha2Code: 'CA',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['canada'],
      es: ['canadá', 'canada'],
      pt: ['canadá', 'canada'],
      de: ['kanada'],
    },
    slug: 'canada',
  },
  {
    name: 'Cape Verde',
    isoAlpha2Code: 'CV',
    continents: ['africa'],
    allowedGuesses: {
      en: ['cape verde'],
      es: ['cabo verde'],
      pt: ['cabo verde'],
      de: ['kap verde'],
    },
    slug: 'cape-verde',
  },
  {
    name: 'Cayman Islands',
    isoAlpha2Code: 'KY',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['cayman islands'],
      es: ['islas cayman'],
      pt: ['ilhas cayman'],
      de: ['kaimaninseln'],
    },
    slug: 'cayman-islands',
  },
  {
    name: 'Central African Republic',
    isoAlpha2Code: 'CF',
    continents: ['africa'],
    allowedGuesses: {
      en: ['central african republic'],
      es: ['república centroafricana', 'republica centroafricana'],
      pt: ['república centro-africana', 'republica centro-africana'],
      de: ['zentralafrikanische republik'],
    },
    slug: 'central-african-republic',
  },
  {
    name: 'Chad',
    isoAlpha2Code: 'TD',
    continents: ['africa'],
    allowedGuesses: { en: ['chad'], es: ['chad'], pt: ['chade'], de: ['tschad'] },
    slug: 'chad',
  },
  {
    name: 'Chile',
    isoAlpha2Code: 'CL',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['chile'], es: ['chile'], pt: ['chile'], de: ['chile'] },
    slug: 'chile',
  },
  {
    name: 'China',
    isoAlpha2Code: 'CN',
    continents: ['asia'],
    allowedGuesses: { en: ['china'], es: ['china'], pt: ['china'], de: ['china'] },
    slug: 'china',
  },
  {
    name: "Côte d'Ivoire",
    isoAlpha2Code: 'CI',
    continents: ['africa'],
    allowedGuesses: {
      en: ['cote divoire', 'ivore', 'ivory coast', "cote d'ivoire"],
      es: ['costa de marfil', 'costa marfil'],
      pt: ['costa do marfim', 'costa marfim'],
      de: ['elfenbeinküste', 'elfenbeinkueste'],
    },
    slug: 'cote-d-ivoire',
  },
  {
    name: 'Colombia',
    isoAlpha2Code: 'CO',
    continents: ['southAmerica'],
    allowedGuesses: {
      en: ['colombia'],
      es: ['colombia'],
      pt: ['colômbia', 'colombia'],
      de: ['kolumbien'],
    },
    slug: 'colombia',
  },
  {
    name: 'Comoros',
    isoAlpha2Code: 'KM',
    continents: ['africa'],
    allowedGuesses: { en: ['comoros'], es: ['comoras'], pt: ['comores'], de: ['komoren'] },
    slug: 'comoros',
  },
  {
    name: 'Congo',
    isoAlpha2Code: 'CG',
    continents: ['africa'],
    allowedGuesses: { en: ['congo'], es: ['congo'], pt: ['congo'], de: ['kongo'] },
    slug: 'congo',
  },
  {
    name: 'Cook Islands',
    isoAlpha2Code: 'CK',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['cook islands'],
      es: ['islas cook'],
      pt: ['ilhas cook'],
      de: ['cookinseln'],
    },
    slug: 'cook-islands',
  },
  {
    name: 'Costa Rica',
    isoAlpha2Code: 'CR',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['costa rica'],
      es: ['costa rica'],
      pt: ['costa rica'],
      de: ['costa rica'],
    },
    slug: 'costa-rica',
  },
  {
    name: 'Croatia',
    isoAlpha2Code: 'HR',
    continents: ['europe'],
    allowedGuesses: {
      en: ['croatia'],
      es: ['croacia'],
      pt: ['croácia', 'croacia'],
      de: ['kroatien'],
    },
    slug: 'croatia',
  },
  {
    name: 'Cuba',
    isoAlpha2Code: 'CU',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['cuba'], es: ['cuba'], pt: ['cuba'], de: ['kuba'] },
    slug: 'cuba',
  },
  {
    name: 'Curacao',
    isoAlpha2Code: 'CW',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['curacao'],
      es: ['curaçao', 'curacao'],
      pt: ['curaçao', 'curacao'],
      de: ['curaçao', 'curacao'],
    },
    slug: 'curacao',
  },
  {
    name: 'Cyprus',
    isoAlpha2Code: 'CY',
    continents: ['asia', 'europe'],
    allowedGuesses: { en: ['cyprus'], es: ['chipre'], pt: ['chipre'], de: ['zypern'] },
    slug: 'cyprus',
  },
  {
    name: 'Czech Republic',
    isoAlpha2Code: 'CZ',
    continents: ['europe'],
    allowedGuesses: {
      en: ['czech republic', 'czechia'],
      es: ['república checa', 'chequia'],
      pt: ['república tcheca', 'chequia', 'republica tcheca', 'tchéquia', 'tchequia'],
      de: ['tschechien', 'tschechische republik'],
    },
    slug: 'czech-republic',
  },
  {
    name: 'Democratic Republic of the Congo',
    isoAlpha2Code: 'CD',
    continents: ['africa'],
    allowedGuesses: {
      en: ['democratic republic of the congo', 'drc'],
      es: ['república democrática del congo', 'rdc'],
      pt: ['república democrática do congo', 'rdc'],
      de: ['demokratische republik kongo', 'drk', 'dr kongo'],
    },
    slug: 'democratic-republic-of-the-congo',
  },
  {
    name: 'Denmark',
    isoAlpha2Code: 'DK',
    continents: ['europe'],
    allowedGuesses: {
      en: ['denmark'],
      es: ['dinamarca'],
      pt: ['dinamarca'],
      de: ['dänemark', 'danemark'],
    },
    slug: 'denmark',
  },
  {
    name: 'Djibouti',
    isoAlpha2Code: 'DJ',
    continents: ['africa'],
    allowedGuesses: {
      en: ['djibouti'],
      es: ['yibuti'],
      pt: ['jibuti', 'djibuti'],
      de: ['dschibuti'],
    },
    slug: 'djibouti',
  },
  {
    name: 'Dominica',
    isoAlpha2Code: 'DM',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['dominica'], es: ['dominica'], pt: ['dominica'], de: ['dominica'] },
    slug: 'dominica',
  },
  {
    name: 'Dominican Republic',
    isoAlpha2Code: 'DO',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['dominican republic'],
      es: ['república dominicana', 'republica dominicana'],
      pt: ['república dominicana', 'republica dominicana'],
      de: ['dominikanische republik'],
    },
    slug: 'dominican-republic',
  },
  {
    name: 'Ecuador',
    isoAlpha2Code: 'EC',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['ecuador'], es: ['ecuador'], pt: ['equador'], de: ['ecuador'] },
    slug: 'ecuador',
  },
  {
    name: 'Egypt',
    isoAlpha2Code: 'EG',
    continents: ['africa', 'asia'],
    allowedGuesses: { en: ['egypt'], es: ['egipto'], pt: ['egito'], de: ['ägypten', 'aegypten'] },
    slug: 'egypt',
  },
  {
    name: 'El Salvador',
    isoAlpha2Code: 'SV',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['el salvador'],
      es: ['el salvador'],
      pt: ['el salvador'],
      de: ['el salvador'],
    },
    slug: 'el-salvador',
  },
  {
    name: 'Equatorial Guinea',
    isoAlpha2Code: 'GQ',
    continents: ['africa'],
    allowedGuesses: {
      en: ['equatorial guinea'],
      es: ['guinea ecuatorial'],
      pt: ['guiné equatorial', 'guine equatorial'],
      de: ['äquatorialguinea', 'aequatorialguinea'],
    },
    slug: 'equatorial-guinea',
  },
  {
    name: 'Eritrea',
    isoAlpha2Code: 'ER',
    continents: ['africa'],
    allowedGuesses: {
      en: ['eritrea'],
      es: ['eritrea'],
      pt: ['eritreia', 'eritréia'],
      de: ['eritrea'],
    },
    slug: 'eritrea',
  },
  {
    name: 'Estonia',
    isoAlpha2Code: 'EE',
    continents: ['europe'],
    allowedGuesses: {
      en: ['estonia'],
      es: ['estonia'],
      pt: ['estônia', 'estonia'],
      de: ['estland'],
    },
    slug: 'estonia',
  },
  {
    name: 'Eswatini',
    isoAlpha2Code: 'SZ',
    continents: ['africa'],
    allowedGuesses: {
      en: ['eswatini', 'swaziland'],
      es: ['esuatini', 'suazilandia'],
      pt: ['eswatini', 'suazilândia', 'suazilandia'],
      de: ['eswatini', 'swasiland'],
    },
    slug: 'eswatini',
  },
  {
    name: 'Ethiopia',
    isoAlpha2Code: 'ET',
    continents: ['africa'],
    allowedGuesses: {
      en: ['ethiopia'],
      es: ['etiopía', 'etiopia'],
      pt: ['etiópia', 'etiopia'],
      de: ['äthiopien', 'aethiopien'],
    },
    slug: 'ethiopia',
  },
  {
    name: 'Falkland Islands',
    isoAlpha2Code: 'FK',
    continents: ['southAmerica'],
    allowedGuesses: {
      en: ['falkland islands'],
      es: ['islas malvinas'],
      pt: ['ilhas malvinas'],
      de: ['falklandinseln'],
    },
    slug: 'falkland-islands',
  },
  {
    name: 'Faroe Islands',
    isoAlpha2Code: 'FO',
    continents: ['europe'],
    allowedGuesses: {
      en: ['faroe islands'],
      es: ['islas feroe', 'islas féroe'],
      pt: ['ilhas feroé', 'ilhas feroe'],
      de: ['färöer-inseln', 'faroer-inseln', 'färöer', 'faroer'],
    },
    slug: 'faroe-islands',
  },
  {
    name: 'Fiji',
    isoAlpha2Code: 'FJ',
    continents: ['oceania'],
    allowedGuesses: { en: ['fiji'], es: ['fiyi'], pt: ['fiji'], de: ['fidschi'] },
    slug: 'fiji',
  },
  {
    name: 'Finland',
    isoAlpha2Code: 'FI',
    continents: ['europe'],
    allowedGuesses: {
      en: ['finland'],
      es: ['finlandia'],
      pt: ['finlândia', 'finlandia'],
      de: ['finnland'],
    },
    slug: 'finland',
  },
  {
    name: 'France',
    isoAlpha2Code: 'FR',
    continents: ['europe'],
    allowedGuesses: {
      en: ['france'],
      es: ['francia'],
      pt: ['frança', 'franca'],
      de: ['frankreich'],
    },
    slug: 'france',
  },
  {
    name: 'French Polynesia',
    isoAlpha2Code: 'PF',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['french polynesia'],
      es: ['polinesia francesa'],
      pt: ['polinésia francesa', 'polinesia francesa'],
      de: ['französisch-polynesien', 'franzoesisch-polynesien'],
    },
    slug: 'french-polynesia',
  },
  {
    name: 'French Southern Territories',
    isoAlpha2Code: 'TF',
    continents: ['antarctica'],
    allowedGuesses: {
      en: ['french southern territories'],
      es: ['territorios australes franceses'],
      pt: ['territórios franceses do sul', 'territorios franceses do sul'],
      de: ['französische süd- und antarktisgebiete', 'franzoesische sued- und antarktisgebiete'],
    },
    slug: 'french-southern-territories',
  },
  {
    name: 'Gabon',
    isoAlpha2Code: 'GA',
    continents: ['africa'],
    allowedGuesses: {
      en: ['gabon'],
      es: ['gabón', 'gabon'],
      pt: ['gabão', 'gabao'],
      de: ['gabun'],
    },
    slug: 'gabon',
  },
  {
    name: 'Gambia',
    isoAlpha2Code: 'GM',
    continents: ['africa'],
    allowedGuesses: { en: ['gambia'], es: ['gambia'], pt: ['gâmbia', 'gambia'], de: ['gambia'] },
    slug: 'gambia',
  },
  {
    name: 'Georgia',
    isoAlpha2Code: 'GE',
    continents: ['asia', 'europe'],
    allowedGuesses: {
      en: ['georgia'],
      es: ['georgia'],
      pt: ['geórgia', 'georgia'],
      de: ['georgien'],
    },
    slug: 'georgia',
  },
  {
    name: 'Germany',
    isoAlpha2Code: 'DE',
    continents: ['europe'],
    allowedGuesses: { en: ['germany'], es: ['alemania'], pt: ['alemanha'], de: ['deutschland'] },
    slug: 'germany',
  },
  {
    name: 'Ghana',
    isoAlpha2Code: 'GH',
    continents: ['africa'],
    allowedGuesses: { en: ['ghana'], es: ['ghana'], pt: ['ghana', 'gana'], de: ['ghana'] },
    slug: 'ghana',
  },
  {
    name: 'Gibraltar',
    isoAlpha2Code: 'GI',
    continents: ['europe'],
    allowedGuesses: { en: ['gibraltar'], es: ['gibraltar'], pt: ['gibraltar'], de: ['gibraltar'] },
    slug: 'gibraltar',
  },
  {
    name: 'Greece',
    isoAlpha2Code: 'GR',
    continents: ['europe'],
    allowedGuesses: {
      en: ['greece'],
      es: ['grecia'],
      pt: ['grécia', 'grecia'],
      de: ['griechenland'],
    },
    slug: 'greece',
  },
  {
    name: 'Greenland',
    isoAlpha2Code: 'GL',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['greenland'],
      es: ['groenlandia'],
      pt: ['groenlândia', 'groenlandia'],
      de: ['grönland', 'groenland'],
    },
    slug: 'greenland',
  },
  {
    name: 'Grenada',
    isoAlpha2Code: 'GD',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['grenada'], es: ['granada'], pt: ['granada'], de: ['grenada'] },
    slug: 'grenada',
  },
  {
    name: 'Guam',
    isoAlpha2Code: 'GU',
    continents: ['oceania'],
    allowedGuesses: { en: ['guam'], es: ['guam'], pt: ['guam'], de: ['guam'] },
    slug: 'guam',
  },
  {
    name: 'Guatemala',
    isoAlpha2Code: 'GT',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['guatemala'], es: ['guatemala'], pt: ['guatemala'], de: ['guatemala'] },
    slug: 'guatemala',
  },
  {
    name: 'Guernsey',
    isoAlpha2Code: 'GG',
    continents: ['europe'],
    allowedGuesses: { en: ['guernsey'], es: ['guernsey'], pt: ['guernsey'], de: ['guernsey'] },
    slug: 'guernsey',
  },
  {
    name: 'Guinea',
    isoAlpha2Code: 'GN',
    continents: ['africa'],
    allowedGuesses: { en: ['guinea'], es: ['guinea'], pt: ['guiné', 'guine'], de: ['guinea'] },
    slug: 'guinea',
  },
  {
    name: 'Guinea-Bissau',
    isoAlpha2Code: 'GW',
    continents: ['africa'],
    allowedGuesses: {
      en: ['guinea-bissau'],
      es: ['guinea-bisáu', 'guinea-bisau'],
      pt: ['guiné-bissau', 'guine-bissau'],
      de: ['guinea-bissau'],
    },
    slug: 'guinea-bissau',
  },
  {
    name: 'Guyana',
    isoAlpha2Code: 'GY',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['guyana'], es: ['guyana'], pt: ['guiana'], de: ['guyana'] },
    slug: 'guyana',
  },
  {
    name: 'Haiti',
    isoAlpha2Code: 'HT',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['haiti'], es: ['haití', 'haiti'], pt: ['haiti'], de: ['haiti'] },
    slug: 'haiti',
  },
  {
    name: 'Holy See',
    isoAlpha2Code: 'VA',
    continents: ['europe'],
    allowedGuesses: {
      en: ['holy see', 'vatican city'],
      es: ['santa sede', 'ciudad del vaticano', 'vaticano'],
      pt: ['santa sé', 'santa se', 'cidade do vaticano', 'vaticano'],
      de: ['vatikanstadt', 'vatikan', 'staat vatikanstadt', 'heiliger stuhl'],
    },
    slug: 'holy-see',
  },
  {
    name: 'Honduras',
    isoAlpha2Code: 'HN',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['honduras'], es: ['honduras'], pt: ['honduras'], de: ['honduras'] },
    slug: 'honduras',
  },
  {
    name: 'Hungary',
    isoAlpha2Code: 'HU',
    continents: ['europe'],
    allowedGuesses: {
      en: ['hungary'],
      es: ['hungría', 'hungria'],
      pt: ['hungria'],
      de: ['ungarn'],
    },
    slug: 'hungary',
  },
  {
    name: 'Iceland',
    isoAlpha2Code: 'IS',
    continents: ['europe'],
    allowedGuesses: {
      en: ['iceland'],
      es: ['islandia'],
      pt: ['islândia', 'islandia'],
      de: ['island'],
    },
    slug: 'iceland',
  },
  {
    name: 'India',
    isoAlpha2Code: 'IN',
    continents: ['asia'],
    allowedGuesses: { en: ['india'], es: ['india'], pt: ['índia', 'india'], de: ['indien'] },
    slug: 'india',
  },
  {
    name: 'Indonesia',
    isoAlpha2Code: 'ID',
    continents: ['asia', 'oceania'],
    allowedGuesses: {
      en: ['indonesia'],
      es: ['indonesia'],
      pt: ['indonésia', 'indonesia'],
      de: ['indonesien'],
    },
    slug: 'indonesia',
  },
  {
    name: 'Iran',
    isoAlpha2Code: 'IR',
    continents: ['asia'],
    allowedGuesses: { en: ['iran'], es: ['irán', 'iran'], pt: ['irã', 'ira'], de: ['iran'] },
    slug: 'iran',
  },
  {
    name: 'Iraq',
    isoAlpha2Code: 'IQ',
    continents: ['asia'],
    allowedGuesses: { en: ['iraq'], es: ['iraq'], pt: ['iraque'], de: ['irak'] },
    slug: 'iraq',
  },
  {
    name: 'Ireland',
    isoAlpha2Code: 'IE',
    continents: ['europe'],
    allowedGuesses: { en: ['ireland'], es: ['irlanda'], pt: ['irlanda'], de: ['irland'] },
    slug: 'ireland',
  },
  {
    name: 'Isle of Man',
    isoAlpha2Code: 'IM',
    continents: ['europe'],
    allowedGuesses: {
      en: ['isle of man'],
      es: ['isla de man'],
      pt: ['ilha de man'],
      de: ['isle of man'],
    },
    slug: 'isle-of-man',
  },
  {
    name: 'Israel',
    isoAlpha2Code: 'IL',
    continents: ['asia'],
    allowedGuesses: { en: ['israel'], es: ['israel'], pt: ['israel'], de: ['israel'] },
    slug: 'israel',
  },
  {
    name: 'Italy',
    isoAlpha2Code: 'IT',
    continents: ['europe'],
    allowedGuesses: {
      en: ['italy'],
      es: ['italia', 'italía'],
      pt: ['itália', 'italia'],
      de: ['italien'],
    },
    slug: 'italy',
  },
  {
    name: 'Jamaica',
    isoAlpha2Code: 'JM',
    continents: ['northAmerica'],
    allowedGuesses: { en: ['jamaica'], es: ['jamaica'], pt: ['jamaica'], de: ['jamaika'] },
    slug: 'jamaica',
  },
  {
    name: 'Japan',
    isoAlpha2Code: 'JP',
    continents: ['asia'],
    allowedGuesses: {
      en: ['japan'],
      es: ['japón', 'japon'],
      pt: ['japão', 'japao'],
      de: ['japan'],
    },
    slug: 'japan',
  },
  {
    name: 'Jersey',
    isoAlpha2Code: 'JE',
    continents: ['europe'],
    allowedGuesses: { en: ['jersey'], es: ['jersey'], pt: ['jersey'], de: ['jersey'] },
    slug: 'jersey',
  },
  {
    name: 'Jordan',
    isoAlpha2Code: 'JO',
    continents: ['asia'],
    allowedGuesses: {
      en: ['jordan'],
      es: ['jordania'],
      pt: ['jordânia', 'jordania'],
      de: ['jordanien'],
    },
    slug: 'jordan',
  },
  {
    name: 'Kazakhstan',
    isoAlpha2Code: 'KZ',
    continents: ['asia', 'europe'],
    allowedGuesses: {
      en: ['kazakhstan'],
      es: ['kazajistán', 'kazajistan'],
      pt: ['cazaquistão', 'cazaquistao'],
      de: ['kasachstan'],
    },
    slug: 'kazakhstan',
  },
  {
    name: 'Kenya',
    isoAlpha2Code: 'KE',
    continents: ['africa'],
    allowedGuesses: { en: ['kenya'], es: ['kenia'], pt: ['quênia', 'quenia'], de: ['kenia'] },
    slug: 'kenya',
  },
  {
    name: 'Kiribati',
    isoAlpha2Code: 'KI',
    continents: ['oceania'],
    allowedGuesses: { en: ['kiribati'], es: ['kiribati'], pt: ['kiribati'], de: ['kiribati'] },
    slug: 'kiribati',
  },
  {
    name: 'Korea (North)',
    isoAlpha2Code: 'KP',
    continents: ['asia'],
    allowedGuesses: {
      en: ['north korea', 'korea north', 'korea (north)'],
      es: ['corea del norte', 'corea norte'],
      pt: ['coreia do norte', 'coreia norte'],
      de: ['nordkorea'],
    },
    slug: 'korea-north',
  },
  {
    name: 'Korea (South)',
    isoAlpha2Code: 'KR',
    continents: ['asia'],
    allowedGuesses: {
      en: ['south korea', 'korea south', 'korea (south)'],
      es: ['corea del sur', 'corea sur'],
      pt: ['coreia do sul', 'coreia sul'],
      de: ['südkorea', 'suedkorea'],
    },
    slug: 'korea-south',
  },
  {
    name: 'Kuwait',
    isoAlpha2Code: 'KW',
    continents: ['asia'],
    allowedGuesses: { en: ['kuwait'], es: ['kuwait'], pt: ['kuwait'], de: ['kuwait'] },
    slug: 'kuwait',
  },
  {
    name: 'Kyrgyzstan',
    isoAlpha2Code: 'KG',
    continents: ['asia'],
    allowedGuesses: {
      en: ['kyrgyzstan'],
      es: ['kirguistán', 'kirguistan'],
      pt: ['quirguistão', 'quirguistao'],
      de: ['kirgistan'],
    },
    slug: 'kyrgyzstan',
  },
  {
    name: 'Laos',
    isoAlpha2Code: 'LA',
    continents: ['asia'],
    allowedGuesses: {
      en: ['laos', 'lao pdr'],
      es: ['laos', 'rp laos'],
      pt: ['laos', 'rp laos'],
      de: ['laos'],
    },
    slug: 'laos',
  },
  {
    name: 'Latvia',
    isoAlpha2Code: 'LV',
    continents: ['europe'],
    allowedGuesses: {
      en: ['latvia'],
      es: ['letonia'],
      pt: ['letônia', 'letonia'],
      de: ['lettland'],
    },
    slug: 'latvia',
  },
  {
    name: 'Lebanon',
    isoAlpha2Code: 'LB',
    continents: ['asia'],
    allowedGuesses: {
      en: ['lebanon'],
      es: ['líbano', 'libano'],
      pt: ['líbano', 'libano'],
      de: ['libanon'],
    },
    slug: 'lebanon',
  },
  {
    name: 'Lesotho',
    isoAlpha2Code: 'LS',
    continents: ['africa'],
    allowedGuesses: { en: ['lesotho'], es: ['lesoto'], pt: ['lesoto'], de: ['lesotho'] },
    slug: 'lesotho',
  },
  {
    name: 'Liberia',
    isoAlpha2Code: 'LR',
    continents: ['africa'],
    allowedGuesses: {
      en: ['liberia'],
      es: ['liberia'],
      pt: ['libéria', 'liberia'],
      de: ['liberia'],
    },
    slug: 'liberia',
  },
  {
    name: 'Libya',
    isoAlpha2Code: 'LY',
    continents: ['africa'],
    allowedGuesses: { en: ['libya'], es: ['libia'], pt: ['líbia', 'libia'], de: ['libyen'] },
    slug: 'libya',
  },
  {
    name: 'Liechtenstein',
    isoAlpha2Code: 'LI',
    continents: ['europe'],
    allowedGuesses: {
      en: ['liechtenstein'],
      es: ['liechtenstein'],
      pt: ['liechtenstein'],
      de: ['liechtenstein'],
    },
    slug: 'liechtenstein',
  },
  {
    name: 'Lithuania',
    isoAlpha2Code: 'LT',
    continents: ['europe'],
    allowedGuesses: {
      en: ['lithuania'],
      es: ['lituania'],
      pt: ['lituânia', 'lituania'],
      de: ['litauen'],
    },
    slug: 'lithuania',
  },
  {
    name: 'Luxembourg',
    isoAlpha2Code: 'LU',
    continents: ['europe'],
    allowedGuesses: {
      en: ['luxembourg'],
      es: ['luxemburgo'],
      pt: ['luxemburgo'],
      de: ['luxemburg'],
    },
    slug: 'luxembourg',
  },
  {
    name: 'Madagascar',
    isoAlpha2Code: 'MG',
    continents: ['africa'],
    allowedGuesses: {
      en: ['madagascar'],
      es: ['madagascar'],
      pt: ['madagáscar', 'madagascar'],
      de: ['madagaskar'],
    },
    slug: 'madagascar',
  },
  {
    name: 'Malawi',
    isoAlpha2Code: 'MW',
    continents: ['africa'],
    allowedGuesses: { en: ['malawi'], es: ['malaui'], pt: ['malawi'], de: ['malawi'] },
    slug: 'malawi',
  },
  {
    name: 'Malaysia',
    isoAlpha2Code: 'MY',
    continents: ['asia'],
    allowedGuesses: {
      en: ['malaysia'],
      es: ['malasia'],
      pt: ['malásia', 'malasia'],
      de: ['malaysia'],
    },
    slug: 'malaysia',
  },
  {
    name: 'Maldives',
    isoAlpha2Code: 'MV',
    continents: ['asia'],
    allowedGuesses: { en: ['maldives'], es: ['maldivas'], pt: ['maldivas'], de: ['malediven'] },
    slug: 'maldives',
  },
  {
    name: 'Mali',
    isoAlpha2Code: 'ML',
    continents: ['africa'],
    allowedGuesses: { en: ['mali'], es: ['mali'], pt: ['mali'], de: ['mali'] },
    slug: 'mali',
  },
  {
    name: 'Malta',
    isoAlpha2Code: 'MT',
    continents: ['europe'],
    allowedGuesses: { en: ['malta'], es: ['malta'], pt: ['malta'], de: ['malta'] },
    slug: 'malta',
  },
  {
    name: 'Marshall Islands',
    isoAlpha2Code: 'MH',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['marshall islands'],
      es: ['islas marshall'],
      pt: ['ilhas marshal', 'ilhas marshall'],
      de: ['marshallinseln'],
    },
    slug: 'marshall-islands',
  },
  {
    name: 'Mauritania',
    isoAlpha2Code: 'MR',
    continents: ['africa'],
    allowedGuesses: {
      en: ['mauritania'],
      es: ['mauritania'],
      pt: ['mauritânia', 'mauritania'],
      de: ['mauretanien'],
    },
    slug: 'mauritania',
  },
  {
    name: 'Mauritius',
    isoAlpha2Code: 'MU',
    continents: ['africa'],
    allowedGuesses: {
      en: ['mauritius'],
      es: ['mauricio'],
      pt: ['maurício', 'mauricio'],
      de: ['mauritius'],
    },
    slug: 'mauritius',
  },
  {
    name: 'Mexico',
    isoAlpha2Code: 'MX',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['mexico'],
      es: ['méxico', 'mexico'],
      pt: ['méxico', 'mexico'],
      de: ['mexiko'],
    },
    slug: 'mexico',
  },
  {
    name: 'Micronesia',
    isoAlpha2Code: 'FM',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['micronesia'],
      es: ['micronesia'],
      pt: ['micronésia', 'micronesia'],
      de: ['mikronesien'],
    },
    slug: 'micronesia',
  },
  {
    name: 'Moldova',
    isoAlpha2Code: 'MD',
    continents: ['europe'],
    allowedGuesses: {
      en: ['moldova'],
      es: ['moldavia'],
      pt: ['moldávia', 'moldavia'],
      de: ['moldawien', 'moldau'],
    },
    slug: 'moldova',
  },
  {
    name: 'Monaco',
    isoAlpha2Code: 'MC',
    continents: ['europe'],
    allowedGuesses: {
      en: ['monaco'],
      es: ['mónaco', 'monaco'],
      pt: ['mônaco', 'monaco'],
      de: ['monaco'],
    },
    slug: 'monaco',
  },
  {
    name: 'Mongolia',
    isoAlpha2Code: 'MN',
    continents: ['asia'],
    allowedGuesses: {
      en: ['mongolia'],
      es: ['mongolia'],
      pt: ['mongólia', 'mongolia'],
      de: ['mongolei'],
    },
    slug: 'mongolia',
  },
  {
    name: 'Montenegro',
    isoAlpha2Code: 'ME',
    continents: ['europe'],
    allowedGuesses: {
      en: ['montenegro'],
      es: ['montenegro'],
      pt: ['montenegro'],
      de: ['montenegro'],
    },
    slug: 'montenegro',
  },
  {
    name: 'Montserrat',
    isoAlpha2Code: 'MS',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['montserrat'],
      es: ['montserrat'],
      pt: ['montserrat'],
      de: ['montserrat'],
    },
    slug: 'montserrat',
  },
  {
    name: 'Morocco',
    isoAlpha2Code: 'MA',
    continents: ['africa'],
    allowedGuesses: { en: ['morocco'], es: ['marruecos'], pt: ['marrocos'], de: ['marokko'] },
    slug: 'morocco',
  },
  {
    name: 'Mozambique',
    isoAlpha2Code: 'MZ',
    continents: ['africa'],
    allowedGuesses: {
      en: ['mozambique'],
      es: ['mozambique'],
      pt: ['moçambique', 'mozambique'],
      de: ['mosambik'],
    },
    slug: 'mozambique',
  },
  {
    name: 'Myanmar',
    isoAlpha2Code: 'MM',
    continents: ['asia'],
    allowedGuesses: {
      en: ['myanmar', 'burma'],
      es: ['myanmar', 'birmania', 'birmania'],
      pt: ['myanmar', 'birmânia', 'birmania'],
      de: ['myanmar', 'birma'],
    },
    slug: 'myanmar',
  },
  {
    name: 'Namibia',
    isoAlpha2Code: 'NA',
    continents: ['africa'],
    allowedGuesses: {
      en: ['namibia'],
      es: ['namibia'],
      pt: ['namíbia', 'namibia'],
      de: ['namibia'],
    },
    slug: 'namibia',
  },
  {
    name: 'Nauru',
    isoAlpha2Code: 'NR',
    continents: ['oceania'],
    allowedGuesses: { en: ['nauru'], es: ['nauru'], pt: ['nauru'], de: ['nauru'] },
    slug: 'nauru',
  },
  {
    name: 'Nepal',
    isoAlpha2Code: 'NP',
    continents: ['asia'],
    allowedGuesses: { en: ['nepal'], es: ['nepal'], pt: ['népal', 'nepal'], de: ['nepal'] },
    slug: 'nepal',
  },
  {
    name: 'Netherlands',
    isoAlpha2Code: 'NL',
    continents: ['europe'],
    allowedGuesses: {
      en: ['netherlands'],
      es: ['países bajos', 'paises bajos', 'holanda'],
      pt: ['países baixos', 'paises baixos', 'holanda'],
      de: ['niederlande', 'holland'],
    },
    slug: 'netherlands',
  },
  {
    name: 'New Caledonia',
    isoAlpha2Code: 'NC',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['new caledonia'],
      es: ['nueva caledonia'],
      pt: ['nova caledônia', 'nova caledonia'],
      de: ['neukaledonien'],
    },
    slug: 'new-caledonia',
  },
  {
    name: 'New Zealand',
    isoAlpha2Code: 'NZ',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['new zealand'],
      es: ['nueva zelanda'],
      pt: ['nova zelândia', 'nova zelândia', 'nova zelandia'],
      de: ['neuseeland'],
    },
    slug: 'new-zealand',
  },
  {
    name: 'Nicaragua',
    isoAlpha2Code: 'NI',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['nicaragua'],
      es: ['nicaragua'],
      pt: ['nicarágua', 'nicaragua'],
      de: ['nicaragua'],
    },
    slug: 'nicaragua',
  },
  {
    name: 'Niger',
    isoAlpha2Code: 'NE',
    continents: ['africa'],
    allowedGuesses: {
      en: ['niger'],
      es: ['níger', 'niger'],
      pt: ['níger', 'niger'],
      de: ['niger'],
    },
    slug: 'niger',
  },
  {
    name: 'Nigeria',
    isoAlpha2Code: 'NG',
    continents: ['africa'],
    allowedGuesses: {
      en: ['nigeria'],
      es: ['nigeria'],
      pt: ['nigéria', 'nigeria'],
      de: ['nigeria'],
    },
    slug: 'nigeria',
  },
  {
    name: 'Niue',
    isoAlpha2Code: 'NU',
    continents: ['oceania'],
    allowedGuesses: { en: ['niue'], es: ['niue'], pt: ['niue'], de: ['niue'] },
    slug: 'niue',
  },
  {
    name: 'North Macedonia',
    isoAlpha2Code: 'MK',
    continents: ['europe'],
    allowedGuesses: {
      en: ['north macedonia'],
      es: ['macedonia del norte', 'macedonia norte'],
      pt: ['macedônia do norte', 'macedonia do norte'],
      de: ['nordmazedonien', 'nord-mazedonien'],
    },
    slug: 'north-macedonia',
  },
  {
    name: 'Northern Mariana Islands',
    isoAlpha2Code: 'MP',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['northern mariana islands'],
      es: ['islas marianas del norte'],
      pt: ['ilhas marianas do norte'],
      de: ['nördliche marianeninseln', 'noerdliche marianeninseln'],
    },
    slug: 'northern-mariana-islands',
  },
  {
    name: 'Norway',
    isoAlpha2Code: 'NO',
    continents: ['europe'],
    allowedGuesses: { en: ['norway'], es: ['noruega'], pt: ['noruega'], de: ['norwegen'] },
    slug: 'norway',
  },
  {
    name: 'Oman',
    isoAlpha2Code: 'OM',
    continents: ['asia'],
    allowedGuesses: { en: ['oman'], es: ['oman'], pt: ['omã', 'oma'], de: ['oman'] },
    slug: 'oman',
  },
  {
    name: 'Pakistan',
    isoAlpha2Code: 'PK',
    continents: ['asia'],
    allowedGuesses: {
      en: ['pakistan'],
      es: ['pakistán', 'pakistan'],
      pt: ['paquistão', 'paquistao'],
      de: ['pakistan'],
    },
    slug: 'pakistan',
  },
  {
    name: 'Palau',
    isoAlpha2Code: 'PW',
    continents: ['oceania'],
    allowedGuesses: { en: ['palau'], es: ['palau'], pt: ['palau'], de: ['palau'] },
    slug: 'palau',
  },
  {
    name: 'Palestine',
    isoAlpha2Code: 'PS',
    continents: ['asia'],
    allowedGuesses: {
      en: ['palestine'],
      es: ['palestina'],
      pt: ['palestina'],
      de: ['palästina', 'palaestina'],
    },
    slug: 'palestine',
  },
  {
    name: 'Panama',
    isoAlpha2Code: 'PA',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['panama'],
      es: ['panamá', 'panama'],
      pt: ['panamá', 'panama'],
      de: ['panama'],
    },
    slug: 'panama',
  },
  {
    name: 'Papua New Guinea',
    isoAlpha2Code: 'PG',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['papua new guinea'],
      es: ['papúa nueva guinea', 'papua nueva guinea'],
      pt: ['papua nova guiné', 'papua nova guine'],
      de: ['papua-neuguinea', 'papua neuguinea'],
    },
    slug: 'papua-new-guinea',
  },
  {
    name: 'Paraguay',
    isoAlpha2Code: 'PY',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['paraguay'], es: ['paraguay'], pt: ['paraguai'], de: ['paraguay'] },
    slug: 'paraguay',
  },
  {
    name: 'Peru',
    isoAlpha2Code: 'PE',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['peru'], es: ['perú', 'peru'], pt: ['peru'], de: ['peru'] },
    slug: 'peru',
  },
  {
    name: 'Philippines',
    isoAlpha2Code: 'PH',
    continents: ['asia'],
    allowedGuesses: {
      en: ['philippines'],
      es: ['filipinas'],
      pt: ['filipinas'],
      de: ['philippinen'],
    },
    slug: 'philippines',
  },
  {
    name: 'Pitcairn',
    isoAlpha2Code: 'PN',
    continents: ['oceania'],
    allowedGuesses: { en: ['pitcairn'], es: ['pitcairn'], pt: ['pitcairn'], de: ['pitcairn'] },
    slug: 'pitcairn',
  },
  {
    name: 'Poland',
    isoAlpha2Code: 'PL',
    continents: ['europe'],
    allowedGuesses: { en: ['poland'], es: ['polonia'], pt: ['polônia', 'polonia'], de: ['polen'] },
    slug: 'poland',
  },
  {
    name: 'Portugal',
    isoAlpha2Code: 'PT',
    continents: ['europe'],
    allowedGuesses: { en: ['portugal'], es: ['portugal'], pt: ['portugal'], de: ['portugal'] },
    slug: 'portugal',
  },
  {
    name: 'Puerto Rico',
    isoAlpha2Code: 'PR',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['puerto rico'],
      es: ['puerto rico'],
      pt: ['porto rico'],
      de: ['puerto rico'],
    },
    slug: 'puerto-rico',
  },
  {
    name: 'Qatar',
    isoAlpha2Code: 'QA',
    continents: ['asia'],
    allowedGuesses: {
      en: ['qatar'],
      es: ['qatar'],
      pt: ['qatar', 'catar'],
      de: ['katar', 'qatar'],
    },
    slug: 'qatar',
  },
  {
    name: 'Romania',
    isoAlpha2Code: 'RO',
    continents: ['europe'],
    allowedGuesses: {
      en: ['romania'],
      es: ['rumania', 'romania'],
      pt: ['romênia', 'romenia'],
      de: ['rumänien', 'rumaenien'],
    },
    slug: 'romania',
  },
  {
    name: 'Russia',
    isoAlpha2Code: 'RU',
    continents: ['europe', 'asia'],
    allowedGuesses: { en: ['russia'], es: ['rusia'], pt: ['rússia', 'russia'], de: ['russland'] },
    slug: 'russia',
  },
  {
    name: 'Rwanda',
    isoAlpha2Code: 'RW',
    continents: ['africa'],
    allowedGuesses: { en: ['rwanda'], es: ['ruanda'], pt: ['ruanda'], de: ['ruanda'] },
    slug: 'rwanda',
  },
  {
    name: 'Saint Barthelemy',
    isoAlpha2Code: 'BL',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['saint barthelemy'],
      es: ['san bartolomé', 'san bartolome'],
      pt: ['são bartolomeu', 'sao bartolomeu'],
      de: ['saint-barthélemy', 'saint-barthelemy'],
    },
    slug: 'saint-barthelemy',
  },
  {
    name: 'Saint Helena',
    isoAlpha2Code: 'SH',
    continents: ['africa'],
    allowedGuesses: {
      en: ['saint helena'],
      es: ['santa helena'],
      pt: ['santa helena'],
      de: ['sankt helena'],
    },
    slug: 'saint-helena',
  },
  {
    name: 'Saint Kitts and Nevis',
    isoAlpha2Code: 'KN',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['saint kitts and nevis'],
      es: ['san cristóbal y nieves', 'san cristobal y nieves'],
      pt: ['são cristóvão e neves', 'sao cristovao e neves'],
      de: ['st. kitts und nevis', 'st kitts und nevis', 'saint kitts und nevis'],
    },
    slug: 'saint-kitts-and-nevis',
  },
  {
    name: 'Saint Lucia',
    isoAlpha2Code: 'LC',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['saint lucia'],
      es: ['santa lucía', 'santa lucia'],
      pt: ['santa lúcia', 'santa lucia'],
      de: ['st. lucia', 'st lucia', 'sankt lucia'],
    },
    slug: 'saint-lucia',
  },
  {
    name: 'Saint Martin',
    isoAlpha2Code: 'MF',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['saint martin'],
      es: ['san martín', 'san martin'],
      pt: ['são martinho', 'sao martinho'],
      de: ['saint-martin'],
    },
    slug: 'saint-martin',
  },
  {
    name: 'Saint Pierre and Miquelon',
    isoAlpha2Code: 'PM',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['saint pierre and miquelon'],
      es: ['san pedro y miquelón', 'san pedro y miquelon'],
      pt: ['são pedro e miquelão', 'sao pedro e miquelao'],
      de: ['saint-pierre und miquelon', 'st pierre und miquelon'],
    },
    slug: 'saint-pierre-and-miquelon',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    isoAlpha2Code: 'VC',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['saint vincent and the grenadines'],
      es: ['san vicente y las granadinas'],
      pt: ['são vicente e granadinas', 'sao vicente e granadinas'],
      de: ['st. vincent und die grenadinen', 'sankt vincent und die grenadinen'],
    },
    slug: 'saint-vincent-and-the-grenadines',
  },
  {
    name: 'Samoa',
    isoAlpha2Code: 'WS',
    continents: ['oceania'],
    allowedGuesses: { en: ['samoa'], es: ['samoa'], pt: ['samoa'], de: ['samoa'] },
    slug: 'samoa',
  },
  {
    name: 'San Marino',
    isoAlpha2Code: 'SM',
    continents: ['europe'],
    allowedGuesses: {
      en: ['san marino'],
      es: ['san marino'],
      pt: ['são marinho', 'sao marinho'],
      de: ['san marino'],
    },
    slug: 'san-marino',
  },
  {
    name: 'Sao Tome and Principe',
    isoAlpha2Code: 'ST',
    continents: ['africa'],
    allowedGuesses: {
      en: ['sao tome and principe'],
      es: ['santo tomé y príncipe', 'santo tome y principe'],
      pt: ['são tomé e príncipe', 'sao tome e principe'],
      de: ['são tomé und príncipe', 'sao tome und principe'],
    },
    slug: 'sao-tome-and-principe',
  },
  {
    name: 'Saudi Arabia',
    isoAlpha2Code: 'SA',
    continents: ['asia'],
    allowedGuesses: {
      en: ['saudi arabia'],
      es: ['arabia saudita'],
      pt: ['arábia saudita', 'arabia saudita'],
      de: ['saudi-arabien', 'saudi arabien'],
    },
    slug: 'saudi-arabia',
  },
  {
    name: 'Senegal',
    isoAlpha2Code: 'SN',
    continents: ['africa'],
    allowedGuesses: { en: ['senegal'], es: ['senegal'], pt: ['senegal'], de: ['senegal'] },
    slug: 'senegal',
  },
  {
    name: 'Serbia',
    isoAlpha2Code: 'RS',
    continents: ['europe'],
    allowedGuesses: { en: ['serbia'], es: ['serbia'], pt: ['sérvia', 'servia'], de: ['serbien'] },
    slug: 'serbia',
  },
  {
    name: 'Seychelles',
    isoAlpha2Code: 'SC',
    continents: ['africa'],
    allowedGuesses: {
      en: ['seychelles'],
      es: ['seychelles'],
      pt: ['seychelles'],
      de: ['seychellen'],
    },
    slug: 'seychelles',
  },
  {
    name: 'Sierra Leone',
    isoAlpha2Code: 'SL',
    continents: ['africa'],
    allowedGuesses: {
      en: ['sierra leone'],
      es: ['sierra leona'],
      pt: ['sierra leoa'],
      de: ['sierra leone'],
    },
    slug: 'sierra-leone',
  },
  {
    name: 'Singapore',
    isoAlpha2Code: 'SG',
    continents: ['asia'],
    allowedGuesses: { en: ['singapore'], es: ['singapur'], pt: ['singapura'], de: ['singapur'] },
    slug: 'singapore',
  },
  {
    name: 'Sint Maarten',
    isoAlpha2Code: 'SX',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['sint maarten'],
      es: ['sint maarten'],
      pt: ['sint maarten'],
      de: ['sint maarten'],
    },
    slug: 'sint-maarten',
  },
  {
    name: 'Slovakia',
    isoAlpha2Code: 'SK',
    continents: ['europe'],
    allowedGuesses: {
      en: ['slovakia'],
      es: ['eslovaquia'],
      pt: ['eslováquia', 'eslovaquia'],
      de: ['slowakei'],
    },
    slug: 'slovakia',
  },
  {
    name: 'Slovenia',
    isoAlpha2Code: 'SI',
    continents: ['europe'],
    allowedGuesses: {
      en: ['slovenia'],
      es: ['eslovenia'],
      pt: ['eslovênia', 'eslovenia'],
      de: ['slowenien'],
    },
    slug: 'slovenia',
  },
  {
    name: 'Solomon Islands',
    isoAlpha2Code: 'SB',
    continents: ['oceania'],
    allowedGuesses: {
      en: ['solomon islands'],
      es: ['islas salomón', 'islas salomon'],
      pt: ['ilhas salomão', 'ilhas salomao'],
      de: ['salomonen', 'salomoninseln'],
    },
    slug: 'solomon-islands',
  },
  {
    name: 'Somalia',
    isoAlpha2Code: 'SO',
    continents: ['africa'],
    allowedGuesses: {
      en: ['somalia'],
      es: ['somalia'],
      pt: ['somália', 'somalia'],
      de: ['somalia'],
    },
    slug: 'somalia',
  },
  {
    name: 'South Africa',
    isoAlpha2Code: 'ZA',
    continents: ['africa'],
    allowedGuesses: {
      en: ['south africa'],
      es: ['sudáfrica', 'sudafrica'],
      pt: ['áfrica do sul', 'africa do sul'],
      de: ['südafrika', 'suedafrika'],
    },
    slug: 'south-africa',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    isoAlpha2Code: 'GS',
    continents: ['antarctica'],
    allowedGuesses: {
      en: ['south georgia and the south sandwich islands'],
      es: [
        'georgia del sur y las islas sandwich del sur',
        'georgia del sur y las islas sandwich del sur',
      ],
      pt: [
        'geórgia do sul e as ilhas sandwich do sul',
        'georgia do sul e as ilhas sandwich do sul',
      ],
      de: [
        'südgeorgien und die südlichen sandwichinseln',
        'suedgeorgien und die suedlichen sandwichinseln',
      ],
    },
    slug: 'south-georgia-and-the-south-sandwich-islands',
  },
  {
    name: 'South Sudan',
    isoAlpha2Code: 'SS',
    continents: ['africa'],
    allowedGuesses: {
      en: ['south sudan'],
      es: ['sudán del sur', 'sudan del sur'],
      pt: ['sudão do sul', 'sudao do sul'],
      de: ['südsudan', 'suedsudan'],
    },
    slug: 'south-sudan',
  },
  {
    name: 'Spain',
    isoAlpha2Code: 'ES',
    continents: ['europe'],
    allowedGuesses: { en: ['spain'], es: ['españa', 'espana'], pt: ['espanha'], de: ['spanien'] },
    slug: 'spain',
  },
  {
    name: 'Sri Lanka',
    isoAlpha2Code: 'LK',
    continents: ['asia'],
    allowedGuesses: { en: ['sri lanka'], es: ['sri lanka'], pt: ['sri lanka'], de: ['sri lanka'] },
    slug: 'sri-lanka',
  },
  {
    name: 'Sudan',
    isoAlpha2Code: 'SD',
    continents: ['africa'],
    allowedGuesses: {
      en: ['sudan'],
      es: ['sudán', 'sudan'],
      pt: ['sudão', 'sudao'],
      de: ['sudan'],
    },
    slug: 'sudan',
  },
  {
    name: 'Suriname',
    isoAlpha2Code: 'SR',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['suriname'], es: ['surinam'], pt: ['suriname'], de: ['suriname'] },
    slug: 'suriname',
  },
  {
    name: 'Sweden',
    isoAlpha2Code: 'SE',
    continents: ['europe'],
    allowedGuesses: {
      en: ['sweden'],
      es: ['suecia'],
      pt: ['suécia', 'suécia', 'suecia'],
      de: ['schweden'],
    },
    slug: 'sweden',
  },
  {
    name: 'Switzerland',
    isoAlpha2Code: 'CH',
    continents: ['europe'],
    allowedGuesses: {
      en: ['switzerland'],
      es: ['suiza'],
      pt: ['suíça', 'suica', 'suiça'],
      de: ['schweiz'],
    },
    slug: 'switzerland',
  },
  {
    name: 'Syrian Arab Republic',
    isoAlpha2Code: 'SY',
    continents: ['asia'],
    allowedGuesses: {
      en: ['syria', 'syrian arab republic'],
      es: ['siria', 'república árabe siria'],
      pt: ['síria', 'siria', 'república árabe síria', 'republica arabe siria'],
      de: ['syrien', 'syrische arabische republik'],
    },
    slug: 'syrian-arab-republic',
  },
  {
    name: 'Taiwan',
    isoAlpha2Code: 'TW',
    continents: ['asia'],
    allowedGuesses: { en: ['taiwan'], es: ['taiwán', 'taiwan'], pt: ['taiwan'], de: ['taiwan'] },
    slug: 'taiwan',
  },
  {
    name: 'Tajikistan',
    isoAlpha2Code: 'TJ',
    continents: ['asia'],
    allowedGuesses: {
      en: ['tajikistan'],
      es: ['tajikistán', 'tajikistan'],
      pt: ['tajiquistão', 'tajiquistao'],
      de: ['tadschikistan'],
    },
    slug: 'tajikistan',
  },
  {
    name: 'Tanzania',
    isoAlpha2Code: 'TZ',
    continents: ['africa'],
    allowedGuesses: {
      en: ['tanzania'],
      es: ['tanzania'],
      pt: ['tanzânia', 'tanzania'],
      de: ['tansania'],
    },
    slug: 'tanzania',
  },
  {
    name: 'Thailand',
    isoAlpha2Code: 'TH',
    continents: ['asia'],
    allowedGuesses: {
      en: ['thailand'],
      es: ['tailandia'],
      pt: ['tailândia', 'tailandia'],
      de: ['thailand'],
    },
    slug: 'thailand',
  },
  {
    name: 'Timor-Leste',
    isoAlpha2Code: 'TL',
    continents: ['asia'],
    allowedGuesses: {
      en: ['timor-leste', 'east timor'],
      es: ['timor oriental', 'timor-leste'],
      pt: ['timor-leste', 'timor leste'],
      de: ['timor-leste', 'osttimor', 'ost timor'],
    },
    slug: 'timor-leste',
  },
  {
    name: 'Togo',
    isoAlpha2Code: 'TG',
    continents: ['africa'],
    allowedGuesses: { en: ['togo'], es: ['togo'], pt: ['togo'], de: ['togo'] },
    slug: 'togo',
  },
  {
    name: 'Tokelau',
    isoAlpha2Code: 'TK',
    continents: ['oceania'],
    allowedGuesses: { en: ['tokelau'], es: ['tokelau'], pt: ['tokelau'], de: ['tokelau'] },
    slug: 'tokelau',
  },
  {
    name: 'Tonga',
    isoAlpha2Code: 'TO',
    continents: ['oceania'],
    allowedGuesses: { en: ['tonga'], es: ['tonga'], pt: ['tonga'], de: ['tonga'] },
    slug: 'tonga',
  },
  {
    name: 'Trinidad and Tobago',
    isoAlpha2Code: 'TT',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['trinidad and tobago'],
      es: ['trinidad y tobago'],
      pt: ['trindade e tobago', 'trindade & tobago'],
      de: ['trinidad und tobago'],
    },
    slug: 'trinidad-and-tobago',
  },
  {
    name: 'Tunisia',
    isoAlpha2Code: 'TN',
    continents: ['africa'],
    allowedGuesses: {
      en: ['tunisia'],
      es: ['túnez', 'tunez'],
      pt: ['túnis', 'tunis'],
      de: ['tunesien'],
    },
    slug: 'tunisia',
  },
  {
    name: 'Turkey',
    isoAlpha2Code: 'TR',
    continents: ['asia', 'europe'],
    allowedGuesses: {
      en: ['turkey'],
      es: ['turquía', 'turquia'],
      pt: ['turquia', 'turquía'],
      de: ['türkei', 'tuerkei'],
    },
    slug: 'turkey',
  },
  {
    name: 'Turkmenistan',
    isoAlpha2Code: 'TM',
    continents: ['asia'],
    allowedGuesses: {
      en: ['turkmenistan'],
      es: ['turkmenistán', 'turkmenistan'],
      pt: ['turcomenistão', 'turcomenistao'],
      de: ['turkmenistan'],
    },
    slug: 'turkmenistan',
  },
  {
    name: 'Tuvalu',
    isoAlpha2Code: 'TV',
    continents: ['oceania'],
    allowedGuesses: { en: ['tuvalu'], es: ['tuvalu'], pt: ['tuvalu'], de: ['tuvalu'] },
    slug: 'tuvalu',
  },
  {
    name: 'Uganda',
    isoAlpha2Code: 'UG',
    continents: ['africa'],
    allowedGuesses: { en: ['uganda'], es: ['uganda'], pt: ['uganda'], de: ['uganda'] },
    slug: 'uganda',
  },
  {
    name: 'Ukraine',
    isoAlpha2Code: 'UA',
    continents: ['europe'],
    allowedGuesses: {
      en: ['ukraine'],
      es: ['ucrania'],
      pt: ['ucrânia', 'ucrania'],
      de: ['ukraine'],
    },
    slug: 'ukraine',
  },
  {
    name: 'United Arab Emirates',
    isoAlpha2Code: 'AE',
    continents: ['asia'],
    allowedGuesses: {
      en: ['united arab emirates', 'uae'],
      es: ['emiratos árabes unidos', 'emiratos arabes unidos'],
      pt: ['emirados árabes unidos', 'emirados arabes unidos'],
      de: ['vereinigte arabische emirate', 'vae'],
    },
    slug: 'united-arab-emirates',
  },
  {
    name: 'United Kingdom',
    isoAlpha2Code: 'GB',
    continents: ['europe'],
    allowedGuesses: {
      en: ['united kingdom', 'uk', 'great britain'],
      es: ['reino unido', 'gran bretaña'],
      pt: ['reino unido', 'grã-bretanha', 'gra-bretanha'],
      de: [
        'vereinigtes königreich',
        'vereinigtes koenigreich',
        'grossbritannien',
        'großbritannien',
        'uk',
      ],
    },
    slug: 'united-kingdom',
  },
  {
    name: 'United States',
    isoAlpha2Code: 'US',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['united states', 'usa'],
      es: ['estados unidos', 'eeuu'],
      pt: ['estados unidos', 'eua'],
      de: ['vereinigte staaten', 'usa'],
    },
    slug: 'united-states',
  },
  {
    name: 'United States Virgin Islands',
    isoAlpha2Code: 'VI',
    continents: ['northAmerica'],
    allowedGuesses: {
      en: ['united states virgin islands', 'us virgin islands'],
      es: ['islas vírgenes de estados unidos', 'islas virgenes de estados unidos'],
      pt: ['ilhas virgens dos estados unidos', 'ilhas virgens eua'],
      de: ['amerikanische jungferninseln', 'amerikanische jungfern-inseln', 'us-jungferninseln'],
    },
    slug: 'united-states-virgin-islands',
  },
  {
    name: 'Uruguay',
    isoAlpha2Code: 'UY',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['uruguay'], es: ['uruguay'], pt: ['uruguai'], de: ['uruguay'] },
    slug: 'uruguay',
  },
  {
    name: 'Uzbekistan',
    isoAlpha2Code: 'UZ',
    continents: ['asia'],
    allowedGuesses: {
      en: ['uzbekistan'],
      es: ['uzbekistán', 'uzbekistan'],
      pt: ['uzbequistão', 'uzbequistao'],
      de: ['usbekistan'],
    },
    slug: 'uzbekistan',
  },
  {
    name: 'Vanuatu',
    isoAlpha2Code: 'VU',
    continents: ['oceania'],
    allowedGuesses: { en: ['vanuatu'], es: ['vanuatu'], pt: ['vanuatu'], de: ['vanuatu'] },
    slug: 'vanuatu',
  },
  {
    name: 'Venezuela',
    isoAlpha2Code: 'VE',
    continents: ['southAmerica'],
    allowedGuesses: { en: ['venezuela'], es: ['venezuela'], pt: ['venezuela'], de: ['venezuela'] },
    slug: 'venezuela',
  },
  {
    name: 'Vietnam',
    isoAlpha2Code: 'VN',
    continents: ['asia'],
    allowedGuesses: {
      en: ['vietnam'],
      es: ['vietnam', 'vietnamita'],
      pt: ['vietnam', 'vietna'],
      de: ['vietnam'],
    },
    slug: 'vietnam',
  },
  {
    name: 'Yemen',
    isoAlpha2Code: 'YE',
    continents: ['asia'],
    allowedGuesses: { en: ['yemen'], es: ['yemen'], pt: ['iemen', 'yemen'], de: ['jemen'] },
    slug: 'yemen',
  },
  {
    name: 'Zambia',
    isoAlpha2Code: 'ZM',
    continents: ['africa'],
    allowedGuesses: { en: ['zambia'], es: ['zambia'], pt: ['zâmbia', 'zambia'], de: ['sambia'] },
    slug: 'zambia',
  },
  {
    name: 'Zimbabwe',
    isoAlpha2Code: 'ZW',
    continents: ['africa'],
    allowedGuesses: {
      en: ['zimbabwe'],
      es: ['zimbabue'],
      pt: ['zimbábue', 'zimbabue'],
      de: ['simbabwe'],
    },
    slug: 'zimbabwe',
  },
] as const

export const countries: Country[] = baseCountries.map((country) => ({
  ...country,
  allowedGuesses: {
    ...country.allowedGuesses,
    zh: chineseNames[country.slug as keyof typeof chineseNames]
      ? [chineseNames[country.slug as keyof typeof chineseNames]]
      : [],
  },
}))

export const europeanCountries: Country[] = countries.filter((country) =>
  country.continents.includes('europe'),
)

export const southAmericaCountries: Country[] = countries.filter((country) =>
  country.continents.includes('southAmerica'),
)

export const northAmericaCountries: Country[] = countries.filter((country) =>
  country.continents.includes('northAmerica'),
)

export const africaCountries: Country[] = countries.filter((country) =>
  country.continents.includes('africa'),
)

export const antarcticaCountries: Country[] = countries.filter((country) =>
  country.continents.includes('antarctica'),
)

export const asiaCountries: Country[] = countries.filter((country) =>
  country.continents.includes('asia'),
)

export const oceaniaCountries: Country[] = countries.filter((country) =>
  country.continents.includes('oceania'),
)

export const countriesByContinent: Record<Continent, Country[]> = {
  africa: africaCountries,
  antarctica: antarcticaCountries,
  asia: asiaCountries,
  europe: europeanCountries,
  northAmerica: northAmericaCountries,
  southAmerica: southAmericaCountries,
  oceania: oceaniaCountries,
}
